import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "./components/Navbar";
// import Nvbar from "@/Components/Nvbar";
// import { LoginLink, LogoutLink } from "@kinde-oss/kinde-auth-nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "News-protal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div> 
        <div className='relative '>
          
                
                    
                     <Navbar></Navbar>
                    
                     

                
            
            
        </div>
        </div>
        <main className="container mx-auto mt-8">{children}</main>
      </body>
    </html>
  );
}
